### ISSUE TITLE
Amend redirects after sign up.

### ISSUE THREAD

**Issue by kieranw-8** [michaelmulianto/SEG-Team-Chickaree#1]
When a user signs up, they should automatically be logged in and redirected to a page displaying their personal information.

At present, they are redirected back to the home page.

Once the relevant user stories have been implemented (i.e. log in and view personal information), this functionality should be added.

**Comment by lclarkg18** [comment]
Solved as part of user story 002. Should reconsider the whole design of page maybe. Not sure account page after log in is ideal but let's get the whole back end working first and then we'll worry about what link is going where.

**Comment by lclarkg18** [comment]
> Solved as part of user story 002. Should reconsider the whole design of page maybe. Not sure account page after log in is ideal but let's get the whole back end working first and then we'll worry about what link is going where.

Solved, redirects to club list
