### ISSUE TITLE
Tournament form not take time zone aware date time format causing warning

### ISSUE THREAD

**Issue by lclarkg18** [michaelmulianto/SEG-Team-Chickaree#121]
The tournament form should input a time zone aware date time format because we are using time zone aware dates.

The correct format looks like "2021-11-20T03:04:05+00:00" for gmt for example but should vary according to timezone (do not know how to do this, probably involves getting some constant from settings. In fixtures it's hard coded it so it isn't a problem.

**Comment by kieranw-8** [comment]
Not sure where this is thrown in the code, I believe the +00:00 represents the timezone. I think it is to do with .now()

**Comment by lclarkg18** [comment]
Could be, Kanishk asked me to take care of it. I'm going to need to delegate some of my stuff this week to be able to cope.

**Comment by lclarkg18** [comment]
FIXED! It was 100% my fault, really sorry everyone, solved in X020
