### ISSUE TITLE
Change tournament validation mechanisms

### ISSUE THREAD

**Issue by lclarkg18** [michaelmulianto/SEG-Team-Chickaree#127]
The tournament model should not enforce such harsh restrictions on the dates of the tournament.

start date must be able to be in the past for two reasons:

1. We want to be able to test having past tournament and it's a real hassle (or impossible) to do this is past dates aren't allowed.
2. Data in the DB should be valid throughout the lifetime of the db such that if you call full clean on the data it would still be valid a year later. The cause/implication of this is that tournament is a model that holds an account of tournaments of a chess club, not just future tournaments.

What _should_ be the constraints?
Deadline<Start date<End date.

How should the idea that you can't create a tournament that will take place in the past be enforced?
In the form for organise tournament.
That way users can't create past tournaments but admins/devs can.

I'm aware that this leaves a weaker protection vs our strong constraints that usually involve a 3 way protection (model, view and controller) but this time I think we have to stick to just view.

If we had time I could try to implement the restriction from the controller side (i.e, you can't select a date in the past for start date) but it is unlikely as I doubt it's trivial (at least within my knowledge)

**Comment by kieranw-8** [comment]
In progress on 030.4
