### ISSUE TITLE
Fixtures user pk

### ISSUE THREAD

**Issue by lclarkg18** [michaelmulianto/SEG-Team-Chickaree#128]
Why is default user pk 999? I meant there's nothing inherently wrong about it, it's just a little unintuitive.

Could we have the default and other users start at 1 and the extra users required for tournament fixtures be beyond that?

**Comment by kieranw-8** [comment]
The users in default tournament participants fixture are generated with a script and thus use 1,2,3.... etc. Will look at regenerating these fixtures again with manually set PKs at some point but this is very very low priority.
