### ISSUE TITLE
Organise Tournament form says "Looks good!" on invalid time entry.

### ISSUE THREAD

**Issue by kieranw-8** [michaelmulianto/SEG-Team-Chickaree#133]
Following on from #127 : 
The issue raised was fixed however I'm not sure how to change the looks good message from the view. An error message appears at the top of the page as expected yet the entry field still gives the affirmative. Please can a front-end guru look at this.

**Comment by kieranw-8** [comment]
I have thought of a far better way to implement this constraint so this will no longer be an issue.

**Comment by kieranw-8** [comment]
My new implementation did not solve this issue as anticipated. Re-opening.

**Comment by kieranw-8** [comment]
No error message appears now. The message was a symptom of the view-based validation which is now all done in the model.

**Comment by lclarkg18** [comment]
Solved in X020 by overriding full clean in form
