### ISSUE TITLE
Enforce validation consistency in views

### ISSUE THREAD

**Issue by kieranw-8** [michaelmulianto/SEG-Team-Chickaree#161]
There are often differences in validation implementation in views, i.e. get_object_or_404 vs an if statement plus a message and redirect. I think the latter gives more control over the user experience, and at some point we should go through the views and ensure one or the other is used at every occurrence.

**Comment by lclarkg18** [comment]
Yes, I also think raising error messages is a better approach, I haven't managed to find info online but as a user you hate getting a 404 and not knowing why, redirects let you stay on the page and messages tell you why

**Comment by lclarkg18** [comment]
This has been improved to a certain extent more could be done but shan't because of time constraints
