### ISSUE TITLE
Ensure logged in users do not see home page.

### ISSUE THREAD

**Issue by kieranw-8** [michaelmulianto/SEG-Team-Chickaree#2]
The home page should be dedicated to serving non-logged in users. Once a user is logged in, any attempt to access the homepage should result in a redirect to an appropriate page. 

This could potentially be the page showing their personal information, or the list of clubs they are a member of. Once the user story for an appropriate solution has been added, amend this functionality.

**Comment by lclarkg18** [comment]
Solved as part of user story 002, as mentioned in previous issue, design might require some rethinking
