### ISSUE TITLE
Integrate promotion of members with memberlist

### ISSUE THREAD

**Issue by kieranw-8** [michaelmulianto/SEG-Team-Chickaree#42]
1. Owners should have the option to promote members from the memberlist
2. The view for promotions currently has temporary redirects which should be replaced with the memberlist for the club_id passed to the view as an argument. Tests should also be updated at the same time.

**Comment by lclarkg18** [comment]
Whoever was doing the member list should do this: have a green button for promote and a red button for ban

**Comment by lclarkg18** [comment]
Just realised that is me hahaha.

**Comment by lclarkg18** [comment]
Done in 011 (Was redesigning member list to be able to kick)
