### ISSUE TITLE
Suggestion: normalise url naming

### ISSUE THREAD

**Issue by lclarkg18** [michaelmulianto/SEG-Team-Chickaree#55]
Our url naming is a little chaotic, I'm thinking we could create a standard for naming.

For example, anything club related should start by club, then have the club id and then what it does so:

club/<int:club.id>/apply instead of apply_to_club/<int:club.id>
 and 
club/<int:club.id>/withdraw_application instead of withdraw_application_to_club/<int:club.id>

imo a good example of good naming that we have already used is:

club/<int:club.id>/promote_member/<int:member.id>

**Comment by ukanishk** [comment]
I agree with you.

**Comment by ukanishk** [comment]
Also related to this, we should be consistent with the content as well. For instance, we have Change Profile as the heading for the page with link button 'Edit info' and the URL is edit_account.

**Comment by lclarkg18** [comment]
Also, I'm looking at webpages online and it looks like we could have something like club=1 or something like that, rather than just dumping numbers in randomly which can get very confusing.

**Comment by lclarkg18** [comment]
Team feedback by the man himself turns out to do this: https://i.ibb.co/T8FhQTy/Screenshot-2021-12-03-at-16-06-40.png

**Comment by lclarkg18** [comment]
When Kieran says so

**Comment by lclarkg18** [comment]
Solved in R009 by agreement in meeting on 08/12/2021
