### ISSUE TITLE
Improve test coverage to decorator functions for views

### ISSUE THREAD

**Issue by lclarkg18** [michaelmulianto/SEG-Team-Chickaree#72]
Although not caught by coverage, we have to implement many more tests. As Kieran rightly noticed, when a function takes a club and a member, it needs to check:

(The user is logged in)
The club exists (test non-existent club with id=999)
The member exists (test non-existent member)
The member belongs to the club (test existent member that belong to different club)

This last one hasn't been tested yet and could be a bit tricky but should be tested for full coverage.

Same for an application for instance; the applicant belongs to the specified club therefore test applicant to different existing club.

Remember using a decorator doesn't remove the need for testing (apparently)

I made some double conditioned decorators for memberships and applications to make views more readable but that means 2 tests must come from the use of that decorator.

**Comment by lclarkg18** [comment]
UPDATE: I realised half way through implementation of R006 that club_id can be removed from many views because it is held in membership/application. This still needs reviewing but is probably safe, will do it shortly.

**Comment by lclarkg18** [comment]
Will wait for Kieran to sort out class based views

**Comment by kieranw-8** [comment]
Class based views are (finally) merged.
